# This rule is not used by the project openkruise-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over rollout.kuberik.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openkruise-controller
    app.kubernetes.io/managed-by: kustomize
  name: rollouttest-admin-role
rules:
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests
  verbs:
  - '*'
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests/status
  verbs:
  - get
