# This rule is not used by the project openkruise-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the rollout.kuberik.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openkruise-controller
    app.kubernetes.io/managed-by: kustomize
  name: rollouttest-editor-role
rules:
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests/status
  verbs:
  - get
