# This rule is not used by the project openkruise-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to rollout.kuberik.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openkruise-controller
    app.kubernetes.io/managed-by: kustomize
  name: rollouttest-viewer-role
rules:
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rollout.kuberik.com
  resources:
  - rollouttests/status
  verbs:
  - get
